name: Daily Newsletter Update

on:
  schedule:
    - cron: '0 8 * * *'   # 08:00 UTC, todos os dias
  workflow_dispatch:

permissions:
  contents: write   # necessário para push com GITHUB_TOKEN

jobs:
  update-newsletter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # precisamos do histórico para diffs/commits

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Update newsletter
        run: node src/updateNewsletter.js

      - name: Commit and push if changed
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add README.md
          if ! git diff --quiet --cached; then
            git commit -m "Update newsletter for $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
