name: Daily Newsletter Update

on:
  schedule:
    # Run every day at 08:00 UTC
    - cron: '0 8 * * *'
  workflow_dispatch: # Allow manual trigger from GitHub UI

permissions:
  contents: write   # Required so the workflow can commit/push changes

jobs:
  update-newsletter:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Full history for diffs/commits

      # 2) Setup Node.js and npm cache
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'  # Use npmjs registry
          always-auth: true  # Ensure auth is sent to the registry

      # 3) (Optional) Sanitize a project .npmrc so it doesn't override our token
      #    Removes any hardcoded _authToken or always-auth lines in the repo .npmrc
      - name: Sanitize project .npmrc
        run: |
          if [ -f .npmrc ]; then
            sed -i.bak -E '/_authToken|always-auth/d' .npmrc
          fi

      # 4) Authenticate with npmjs using an Automation token stored in repo secrets
      - name: Authenticate with npm
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Create this in Settings → Secrets → Actions

      # 5) Install dependencies (works with private packages on npmjs.com)
      - name: Install dependencies
        run: npm ci

      # 6) Run your script that updates the newsletter contents
      - name: Update newsletter
        run: node src/updateNewsletter.js

      # 7) Commit and push changes if anything was modified
      - name: Commit and push if changed
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add README.md
          if ! git diff --quiet --cached; then
            git commit -m "Update newsletter for $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
