name: Daily Newsletter Update

on:
  schedule:
    # Run every day at 8:00 UTC
    - cron: '0 8 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Update newsletter
        run: node src/updateNewsletter.js

      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update newsletter for $(date +'%Y-%m-%d')"
            git remote set-url origin https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
            git push
          )
