jobs:
  update-newsletter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: false

      # Sanitize: remove qualquer .npmrc do runner/projeto e force registry público
      - name: Force public registry only
        run: |
          rm -f ~/.npmrc .npmrc || true
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "always-auth=false" >> .npmrc
          echo "Effective npm registry: $(npm config get registry)"
          echo "Lockfile registries:"
          (grep -Eo 'https?://[^"]+' package-lock.json | sort -u) || echo "no lockfile or no urls"

      - name: Install dependencies
        run: npm ci

      - name: Update newsletter
        run: node src/updateNewsletter.js

      - name: Commit and push if changed
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add README.md
          if ! git diff --quiet --cached; then
            git commit -m "Update newsletter for $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
