name: Daily Newsletter Update

on:
  schedule:
    # Run every day at 08:00 UTC
    - cron: '0 8 * * *'
  # Allow manual triggering
  workflow_dispatch:

permissions:
  contents: write  # needed to push using GITHUB_TOKEN

jobs:
  update-newsletter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for diffs/commits

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: false

      # Force ONLY the public npm registry and remove any leftover auth/overrides
      - name: Force public npm registry only (no tokens)
        run: |
          rm -f ~/.npmrc .npmrc || true
          printf "registry=https://registry.npmjs.org/\nalways-auth=false\n" > .npmrc
          echo "Effective registry: $(npm config get registry)"

      - name: Install dependencies
        run: npm ci

      - name: Update newsletter
        run: node src/updateNewsletter.js

      - name: Commit and push if changed
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add README.md
          if ! git diff --quiet --cached; then
            git commit -m "Update newsletter for $(date -u +'%Y-%m-%d')"
            git push
          else
            echo "No changes to commit."
          fi
