name: Daily Newsletter (Actions)

on:
  schedule:
    # Check twice per hour; we'll gate runs to 1–5 random slots/day
    - cron: "*/30 * * * *"
  workflow_dispatch:

permissions:
  contents: write  # needed to push using GITHUB_TOKEN

jobs:
  run-newsletter:
    runs-on: ubuntu-latest
    env:
      # How many half-hour slots exist in a day
      SLOTS_PER_DAY: "48"

    steps:
      - name: Decide if this slot should run (1–5 random runs/day)
        id: gate
        shell: bash
        run: |
          set -euo pipefail
          TODAY_UTC="$(date -u +'%Y-%m-%d')"
          HOUR="$(date -u +'%H')"
          MIN="$(date -u +'%M')"
          # Current half-hour slot index (0..47)
          if [ "$MIN" -ge 30 ]; then
            CUR_SLOT=$((10#$HOUR * 2 + 1))
          else
            CUR_SLOT=$((10#$HOUR * 2))
          fi

          # Create a deterministic daily seed from date + repo
          # (gives "random" but reproducible per day)
          SEED_HEX="$(printf '%s|%s' "$TODAY_UTC" "${GITHUB_REPOSITORY}" | sha256sum | cut -c1-8)"
          SEED=$((16#$SEED_HEX))

          # Number of runs today: 1..5
          TARGET_RUNS=$(( SEED % 5 + 1 ))

          # Simple LCG to get pseudo-random numbers
          lcg_next () {
            SEED=$(( (1103515245 * SEED + 12345) % 2147483647 ))
            echo $SEED
          }

          # Pick unique half-hour slots for today
          declare -A PICKED=()
          SELECTED_SLOTS=()
          while [ ${#SELECTED_SLOTS[@]} -lt $TARGET_RUNS ]; do
            R=$(lcg_next)
            SLOT=$(( R % ${SLOTS_PER_DAY} ))
            if [ -z "${PICKED[$SLOT]+x}" ]; then
              PICKED[$SLOT]=1
              SELECTED_SLOTS+=("$SLOT")
            fi
          done

          # Sort slots to know the first (earliest) one
          IFS=$'\n' SORTED=($(printf '%s\n' "${SELECTED_SLOTS[@]}" | sort -n))
          FIRST_SLOT="${SORTED[0]}"

          SHOULD_RUN="false"
          for s in "${SELECTED_SLOTS[@]}"; do
            if [ "$s" = "$CUR_SLOT" ]; then
              SHOULD_RUN="true"
              break
            fi
          done

          echo "Today (UTC):             $TODAY_UTC"
          echo "Target runs today:       $TARGET_RUNS"
          echo "Selected half-hour slots: ${SELECTED_SLOTS[*]}"
          echo "Current slot:            $CUR_SLOT"
          echo "First slot today:        $FIRST_SLOT"
          echo "Should run now?          $SHOULD_RUN"

          {
            echo "TODAY_UTC=$TODAY_UTC"
            echo "TARGET_RUNS=$TARGET_RUNS"
            echo "SELECTED_SLOTS=${SELECTED_SLOTS[*]}"
            echo "FIRST_SLOT=$FIRST_SLOT"
            echo "CUR_SLOT=$CUR_SLOT"
            echo "SHOULD_RUN=$SHOULD_RUN"
          } >> "$GITHUB_ENV"

      - name: Checkout repository
        if: env.SHOULD_RUN == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        if: env.SHOULD_RUN == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          always-auth: false

      # Force only public registry, remove any leftover auth files
      - name: Force public npm registry only (no tokens)
        if: env.SHOULD_RUN == 'true'
        run: |
          rm -f ~/.npmrc .npmrc || true
          printf "registry=https://registry.npmjs.org/\nalways-auth=false\n" > .npmrc
          echo "Effective registry: $(npm config get registry)"
          npm ping

      # 🔎 Detect non-public registries/tarballs in package-lock.json
      - name: Inspect lockfile registries and tarballs
        if: env.SHOULD_RUN == 'true'
        run: |
          if [ -f package-lock.json ]; then
            echo "=== URLs found in package-lock.json ==="
            URLS=$(grep -EO '"resolved":\s*"https?://[^"]+' package-lock.json | sed -E 's/^"resolved":\s*"//' | sort -u || true)
            if [ -n "$URLS" ]; then
              echo "$URLS"
            else
              echo "(no resolved URLs found)"
            fi
            echo "=== Non-npmjs URLs (should be empty) ==="
            NON_NPM=$(echo "$URLS" | grep -v 'registry\.npmjs\.org' || true)
            if [ -n "$NON_NPM" ]; then
              echo "$NON_NPM"
              echo "::error::Your lockfile references non-public registries or private tarballs above. Remove/replace those deps or regenerate the lockfile to use the public npm registry only."
              exit 1
            fi
          else
            echo "No package-lock.json found."
          fi

      - name: Configure npm registry
        if: env.SHOULD_RUN == 'true'
        run: npm config set registry https://registry.npmjs.org/

      - name: Clean install dependencies
        if: env.SHOULD_RUN == 'true'
        run: |
          rm -f package-lock.json
          npm install --loglevel=verbose

      - name: Run newsletter update script
        if: env.SHOULD_RUN == 'true'
        run: node src/updateNewsletter.js

      - name: Commit and push if changed (with daily heartbeat)
        if: env.SHOULD_RUN == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          git config user.email "contato@lucascaixeta.com"
          git config user.name "Lucas Caixeta"
          git add README.md || true

          if ! git diff --quiet --cached; then
            git commit -m "Update newsletter for ${TODAY_UTC}"
            git push
            exit 0
          fi

          # If no changes, create a single daily heartbeat commit
          # only on the earliest selected slot for the day
          if [ "${CUR_SLOT}" = "${FIRST_SLOT}" ]; then
            mkdir -p .github
            printf "Heartbeat: %s %s UTC\n" "${TODAY_UTC}" "$(date -u +'%H:%M')" > .github/daily-heartbeat.txt
            git add .github/daily-heartbeat.txt
            git commit -m "Daily heartbeat for ${TODAY_UTC}"
            git push
            echo "Heartbeat commit created."
          else
            echo "No changes to commit and not the first slot — skipping commit."
          fi
